[global]
index-url = https://pypi.tuna.tsinghua.edu.cn/simple
timeout = 6000
proxy = 
trusted-host = pypi.tuna.tsinghua.edu.cn
[pip]
download_index_url = https://pypi.tuna.tsinghua.edu.cn/simple
extra_index_url = 
    https://mirrors.aliyun.com/pypi/simple/
    https://pypi.mirrors.ustc.edu.cn/simple/